name: Build and deploy to MASTER branch

on:
  push:
    branches: [master]

jobs:
  Dockermaster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@main

      - name: Build Backend
        run: |
          sudo npm i --force

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/deockerdemo-node-web-app:latest

      - name: Run the image in a container
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/deockerdemo-node-web-app:latest
          run: |
            echo "runing the docker image"
            echo "Testing the nodejs  app endpoints"
            echo ${{ steps.docker_build.outputs.digest }}

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.VM_SSH_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.VM_KNOWN_HOSTS }}
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)

      - name: ssh to vm and docker pull and run container
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USERNAME}}@${{ secrets.VM_KNOWN_HOSTS }}
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }} "cd /home/ubuntu/Dockerdemo-Amal/;git pull;npm install --force;sudo docker pull amalkr/deockerdemo-node-web-app:latest;sudo docker stop test-docker-amal;sudo docker rm test-docker-amal;sudo docker run -p49160:8080 -d --name=test-docker-amal amalkr/deockerdemo-node-web-app:latest"
  

  
   
  
